### ISSUE TITLE
material variant?

### ISSUE THREAD

**Issue by vtolstov** [start-angular/SB-Admin-BS4-Angular-6#205]
Very nice theme! Does it possible to create material variant of this theme?

**Comment by nitinkumarmishra** [comment]
Sure I will do that probably in next month.

**Comment by ShaunBrassell** [comment]
Fantastic code! Having a well written skeleton like this helps to put all the pieces together, following good coding practices ... which is missing from so many other tutorials. Thank you so much!

Looking forward to the Material Design version ... am guessing it will be similar to MDBootrap, but using your well thought out coding practices?!

And while you are doing such great work, it would be great if you could include some other common pages like one or two variants on Login pages, and maybe a few examples of a landing/home pages. And while I am pushing my luck, a CRUD example with a table, with pagination , ha ha :)

**Comment by nitinkumarmishra** [comment]
https://github.com/start-javascript/sb-admin-material

**Comment by ShaunBrassell** [comment]
You my friend, are amazing!
