### ISSUE TITLE
The banner still shows SB admin Angular 5 BS4

### ISSUE THREAD

**Issue by huangliang10987** [start-angular/SB-Admin-BS4-Angular-6#260]
After running the app, I found the banner still shows SB admin Angular 5 BS4. It's in src\app\layout\components\header\header.component.html

PS: I guess there's no need to make it 6 since 7 is there LOL

**Comment by fabiomartino** [comment]
Fix with this PR.
https://github.com/start-angular/SB-Admin-BS4-Angular-6/pull/261
