### ISSUE TITLE
mat-expansion-panel

### ISSUE THREAD

**Issue by samuelmugi** [start-angular/SB-Admin-BS4-Angular-6#272]
Does this theme really use https://material.angular.io. i have been trying to import the 
<mat-expansion-panel> i keep getting the error 

'mat-panel-title' is not a known element: 1. If 'mat-panel-title' is an Angular component, then verify that it is part of this module. 2. If 'mat-panel-title' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <mat-expansion-panel> <mat-expansion-panel-header> [ERROR ->]<mat-panel-title> Personal data </mat-panel-title> "): ng:///DashboardModule/DashboardComponent.html@41:10 'mat-panel-description' is not a known element: 1. If 'mat-panel-description' is an Angular component, then verify

**Comment by sukheja-varun** [comment]
I checked the package.json it nowhere includes @angular/material, so using any of the angular material tags won't work here. Also in the project description, it is mentioned that this project is based on Angular7 and Bootstrap4, nowhere it says it is based on material.

**Comment by samuelmugi** [comment]
Its Okay. Ifugured out how to do it. By the way it also has angualr material in it.

**Comment by Lerato-Eddie** [comment]
How did you solve it

**Comment by mshamshaddin1** [comment]
How did you solve it? @samuelmugi
